app/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/settings', 'SettingsController@index')->name('settings');
Auth::routes(['verify' => true]);

Route::get('/home', 'ProductSiteController@index')->name('home');


Route::get('/produtos/search/', 'ProductSiteController@search')->name('produtos.search');

Route::resources([
    'produtos' => 'ProductSiteController'
]);

app/app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
        'name', 'brand_id', 'price', 'quantity'
    ];

    private $filtersAvailable = [
        'name', 'brand', 'price', 'quantity'
    ];

    private $sortAvailable = [
        'name', 'price', 'quantity'
    ];

    public function brand()
    {
        return $this->belongsTo(Brand::class);
    }

    public function getFiltersAvailable() {
		return $this->filtersAvailable;
    }
    
    public function getSortAvailable() {
		return $this->sortAvailable;
    }
    
}

app/app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\BaseController;
use App\Product;
use Validator;
use App\Repositories\Contracts\ProductRepositoryInterface;

class ProductController extends BaseController
{
    private $model = null;

    public function __construct(ProductRepositoryInterface $product)
    {
        $this->model = $product;
    }    

    public function index(Request $request)
    {     
        $products = $this->model->getAll($request);
        return $this->sendResponse($products->toArray(), 'Products retrieved successfully.');
    }

    public function store(Request $request)
    {        
         $validator = Validator::make($request->all(), [
            'name' => 'required|string|max:255|unique:products',
            'brand_id' => 'required|max:255',
            'price' => 'required|numeric',
            'quantity' =>'required|integer',
        ]);

        if($validator->fails()){
            return $this->sendError('Validation Error.', $validator->errors());       
        }
             
        $product = $this->model->create($request->only($this->model->getFields()));

        return $this->sendResponse($product->toArray(), 'Product created successfully.');
    }

    public function show($id)
    {
        $product = $this->model->getById($id);

        if (is_null($product)) {
            return $this->sendError('Product not found.');
        }

        return $this->sendResponse($product->toArray(), 'Product retrieved successfully.');
    }

    public function update(Request $request, Product $product)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|string|max:255|unique:products,name,'.$product->id,
            'brand_id' => 'required|max:255',
            'price' => 'required|numeric',
            'quantity' =>'required|integer',
        ]);

        if($validator->fails()){
            return $this->sendError('Validation Error.', $validator->errors());       
        }

        $product = $this->model->update($product, $request->only($this->model->getFields()));     

        return $this->sendResponse($product->toArray(), 'Product updated successfully.');
    }

    public function destroy(Product $product)
    {
        $this->model->delete($product);

        return $this->sendResponse($product->toArray(), 'Product deleted successfully.');
    }
   

}

app/resources/views/product/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Cadastrar Produto</div>
                <div class="card-body">
                <form method="post" action="{{ route('produtos.store') }}">
                @csrf
                    <div class="form-group">
                        <label>Nome:</label> 
                        <input type="text" class="form-control" name="name" value="{{ old('name') }}" placeholder="Informe o nome do produto">  
                        @if ($errors->has('name'))                        
                            <span class="text-danger">
                                <strong>{{ $errors->first('name') }}</strong>
                            </span>
                        @endif
                    </div>

                    <div class="form-group">
                        <label>Marca:</label>
                        @include('partials.cb_brandById')
                       
                        @if ($errors->has('brand'))                        
                            <span class="text-danger">
                                <strong>{{ $errors->first('brand') }}</strong>
                            </span>
                        @endif 
                    </div>

                    <div class="form-group">
                        <label>Preço:</label>
                        <input type="text" class="form-control money" name="price" value="{{ old('price') }}" placeholder="Informe o preço do produto">  
                        @if ($errors->has('price'))                        
                            <span class="text-danger">
                                <strong>{{ $errors->first('price') }}</strong>
                            </span>
                        @endif
                    </div>

                    <div class="form-group">
                        <label>Quantidade:</label>
                        <input type="number" class="form-control" name="quantity" value="{{ old('quantity') }}" placeholder="Informe a quantidade do produto"> 
                        @if ($errors->has('quantity'))                        
                            <span class="text-danger">
                                <strong>{{ $errors->first('quantity') }}</strong>
                            </span>
                        @endif 
                    </div>
                    
                    <button type="submit" class="btn btn-primary">Gravar</button>
                    <a href="/produtos" class="btn btn-link">Voltar</a>
                </form>
                   
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

app/resources/views/product/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Editar Produto</div>
                <div class="card-body">
                <form method="post" action="{{ route('produtos.update', $response['data']['id']) }}">
                @csrf
                @method('PUT')
                    <div class="form-group">
                        <label>Nome:</label>
                        <input type="text" class="form-control" name="name" value="{{ old('name', isset($response['data']['name']) ? $response['data']['name'] : null) }}" placeholder="Informe o nome do produto">  
                        @if ($errors->has('name'))                        
                            <span class="text-danger">
                                <strong>{{ $errors->first('name') }}</strong>
                            </span>
                        @endif
                    </div>

                    <div class="form-group">
                        <label>Marca:</label>
                        
                        @include('partials.cb_brandById')
                        @if ($errors->has('brand'))                        
                            <span class="text-danger">
                                <strong>{{ $errors->first('brand') }}</strong>
                            </span>
                        @endif 
                    </div>

                    <div class="form-group">
                        <label>Preço:</label>
                        <input type="text" class="form-control money" name="price" value="{{ old('price', isset($response['data']['price']) ? number_format($response['data']['price'], 2, ',', '.') : null) }}" placeholder="Informe o preço do produto">  
                        @if ($errors->has('price'))                        
                            <span class="text-danger">
                                <strong>{{ $errors->first('price') }}</strong>
                            </span>
                        @endif
                    </div>

                    <div class="form-group">
                        <label>Quantidade:</label>
                        <input type="number" class="form-control" name="quantity" value="{{ old('quantity', isset($response['data']['quantity']) ? $response['data']['quantity'] : null) }}" placeholder="Informe a quantidade do produto"> 
                        @if ($errors->has('quantity'))                        
                            <span class="text-danger">
                                <strong>{{ $errors->first('quantity') }}</strong>
                            </span>
                        @endif 
                    </div>
                    
                    <button type="submit" class="btn btn-primary">Gravar</button>
                    <a href="/produtos" class="btn btn-link">Voltar</a>
                </form>
                   
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

app/resources/views/product/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Produtos</div>

                <div class="card-body">
                    <nav class="nav">
                        <a class="nav-link active" href="/produtos/create">Novo Produto</a>                        
                    </nav><br>
                   
                   
                    <form method="get" action="{{ route('produtos.search') }}">
                      
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" name="q" value="{{ old('q', isset($request->q) ? $request->q : null) }}" placeholder="Informe o nome do produto para realizar a busca">
                            
                            @include('partials.cb_brandByName')
                            <div class="input-group-append">
                                <button class="btn btn-outline-secondary" type="submit">Buscar</button>
                            </div>
                        </div>
                        <div style="width: 150px; margin-left: 10px;" class="float-right">
                        <select class="custom-select pull-right" name="direction">
                                <option value="asc" {{ ((isset($request->direction) && $request->direction=="asc") ? 'selected' : null) }}>Crescente</option>
                                <option value="desc" {{ ((isset($request->direction) && $request->direction=="desc") ? 'selected' : null) }}>Decrescente</option>
                            </select> 
                        </div>
                        <div style="width: 150px;" class="float-right">
                        <select class="custom-select pull-right" name="sortBy">
                                <option value="" selected>Ordenar por</option>
                                <option value="name" {{ ((isset($request->sortBy) && $request->sortBy=="name") ? 'selected' : null) }}>Nome</option>
                                <option value="price" {{ ((isset($request->sortBy) && $request->sortBy=="price") ? 'selected' : null) }}>Preço</option>
                                <option value="quantity" {{ ((isset($request->sortBy) && $request->sortBy=="quantity") ? 'selected' : null) }}>Quantidade</option>
                            </select> 
                        </div>
                         
                    </form>
                   
                    <br> <br> <br>
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                            <th scope="col">#</th>
                            <th scope="col">Nome</th>
                            <th scope="col">Marca</th>
                            <th scope="col">Quantidade</th>
                            <th scope="col">Preço</th>
                            <th scope="col" width='15%'></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($response['data']['data'] as $value)                               
                                <tr>
                                    <th scope="row">{{ $value['id'] }}</th>
                                    <td>{{ $value['name'] }}</td>
                                    <td>{{ $value['brand']['name'] }}</td>
                                    <td>{{ $value['quantity'] }}</td>
                                    <td>{{ number_format($value['price'], 2, ',', '.') }}</td>
                                    <td> 
                                        <a href="/produtos/{{ $value['id'] }}/edit" class="btn btn-info">Editar</a>
                                        <button type="button" id="{{$value['id']}}" action="/produtos" data-toggle="modal" data-target=".bs-example-modal-sm" class="btnExcluir btn btn-danger">Excluir</button>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                   
                </div>
            </div>
        </div>
    </div>
</div>
@endsection